# Generated by Django 5.2.5 on 2025-08-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
